stages:

- stage: Build
  jobs:

  - job: Build
    pool: Hosted VS2017
    steps:
    - checkout: self
      clean: true

    - task: MSBuild@1
      displayName: Restore
      inputs:
        solution: src/Moq.sln
        configuration: Release
        msbuildArguments: /t:Restore /m /bl:$(Build.ArtifactStagingDirectory)\logs\restore.binlog

    - task: MSBuild@1
      displayName: Version
      inputs:
        solution: src/Moq/Moq.Package/Moq.Package.msbuildproj
        msbuildArguments: /t:Version /bl:$(Build.ArtifactStagingDirectory)\logs\version.binlog

    - task: MSBuild@1
      displayName: Build
      inputs:
        solution: src/Moq.sln
        configuration: Release
        msbuildArguments: /p:PackOnBuild=true /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)\pkg /bl:"$(Build.ArtifactStagingDirectory)\logs\build.binlog" 

    - task: VSTest@2
      displayName: Test
      inputs:
        testAssemblyVer2: src\*\*\bin\*\*.Tests.dll
        runInParallel: 'true'
        codeCoverageEnabled: 'true'
        publishRunAttachments: 'true'
        diagnosticsEnabled: false
        rerunFailedTests: true
    
    - task: PublishBuildArtifacts@1
      displayName: Publish Packages
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)\pkg
        ArtifactName: packages
        ArtifactType: Container
      condition: always()

    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)\logs
        ArtifactName: logs
        ArtifactType: Container
      condition: always()

- stage: Deploy
  jobs:
  - deployment: Deploy
    pool: Hosted VS2017
    environment: kzu-nuget-cloud
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DotNetCoreCLI@2
            displayName: 'install sleet'
            inputs:
            command: custom
            custom: tool
            arguments: 'install -g --version 2.3.79 sleet'

          - script: 'sleet push --config none $(Build.DefinitionName)\packages -f --verbose -p "SLEET_FEED_CONNECTIONSTRING=$(SLEET_FEED_CONNECTIONSTRING)"'
            displayName: 'sleet push'  
